# Generated by Django 4.0.3 on 2023-04-29 03:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('roadmap_url', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='roadmap_icons', verbose_name='Roadmap Icon')),
                ('total_likes', models.PositiveIntegerField(default=38)),
            ],
            options={
                'verbose_name_plural': 'All Roadmaps',
                'ordering': ['-name'],
                'unique_together': {('name', 'roadmap_url')},
            },
        ),
        migrations.CreateModel(
            name='RoadMapList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.PositiveBigIntegerField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaplist', to='roadmap.roadmap')),
            ],
            options={
                'verbose_name_plural': 'Roadmap Lists',
                'ordering': ['roadmap', 'number'],
                'unique_together': {('roadmap', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RoadMapTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150)),
                ('number', models.PositiveBigIntegerField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('roadmaplist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaptopic', to='roadmap.roadmaplist')),
            ],
        ),
    ]
