"""
Django settings for tgbwebsite project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from tgbwebsite.logging import LOGGING
from django.core.exceptions import ImproperlyConfigured
from tgbwebsite.jazzmins import JAZZMIN_UI_TWEAKS, JAZZMIN_SETTINGS
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("The prod tech geek directive has been improperly configured in the .env file")
SECRET_KEY = SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
TECH_PROD = os.getenv("TECH_PROD")
if not TECH_PROD:
    raise ImproperlyConfigured("The prod tech geek directive has been improperly configured in the .env file")
if TECH_PROD == "yeas":
    DEBUG= False
    ALLOWED_HOSTS = ["*", "www.techgeekbuzz.com", "techgeekbuzz.com", "https://techgeekbuzz.com", ]
    SECURE_SSL_REDIRECT = True
else:
    DEBUG = True
    ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    # project custom apps
    'blog.apps.BlogConfig',
    'tutorial.apps.TutorialConfig',
    'users.apps.UsersConfig',
    'adsmanager.apps.AdsmanagerConfig',
    'roadmap.apps.RoadmapConfig',
    'tool.apps.ToolConfig',
    'webstories.apps.WebstoriesConfig',
    
    # third party library
    'tinymce',
    'ckeditor',
    'ckeditor_uploader',
    'crispy_forms',
    'crispy_bootstrap5',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tgbwebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.blog_preprocessor.popularpost',
                'tutorial.tutorial_preprocessor.alltutorials',
            ],
        },
    },
]

WSGI_APPLICATION = 'tgbwebsite.wsgi.application'
APPEND_SLASH=True
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASE_ENGINE = os.getenv("DATABASE_ENGINE")
if not DATABASE_ENGINE:
    raise ImproperlyConfigured("The prod database engine directive has been improperly configured in the .env file")
DATABASE_NAME = os.getenv("DATABASE_NAME")
if not DATABASE_NAME:
    raise ImproperlyConfigured("The prod database bane directive has been improperly configured in the .env file")
DATABASE_USER = os.getenv("DATABASE_USER")
if not DATABASE_USER:
    raise ImproperlyConfigured("The prod database user directive has been improperly configured in the .env file")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
if not DATABASE_PASSWORD:
    raise ImproperlyConfigured("The prod database password directive has been improperly configured in the .env file")
DATABASE_HOST = os.getenv("DATABASE_HOST")
if not DATABASE_HOST:
    raise ImproperlyConfigured("The prod database host directive has been improperly configured in the .env file")
if TECH_PROD == "yes":
    DATABASES = {
        'default': {
            'ENGINE': DATABASE_ENGINE,
            'NAME': DATABASE_NAME,
            'USER': DATABASE_USER,
            'PASSWORD': DATABASE_PASSWORD,
            'HOST': DATABASE_HOST,
            }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_UI_TWEAKS = JAZZMIN_UI_TWEAKS
JAZZMIN_SETTINGS = JAZZMIN_SETTINGS

CKEDITOR_CONFIGS = {
    'default': {
        # 'skin': 'basic',
        # 'skin': 'office2013',
      
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
             
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar',  'Iframe']},
            
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['ShowBlocks']},
            
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Source',
                'Maximize',
                'CodeSnippet',
                'Embed',
            ]},
        ],
     
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        'height': "100vh",
        'width': '100%',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
         'codeSnippet_languages' : {'apache': 'Apache',
						'bash': 'Bash',
						'coffeescript': 'CoffeeScript',
                        'c':'C',
						'cpp': 'C++',
						'cs': 'C#',
						'css': 'CSS',
						'diff': 'Diff',
						'html': 'HTML',
						'http': 'HTTP',
						'ini': 'INI',
						'java': 'Java',
						'javascript': 'JavaScript',
						'json': 'JSON',
						'makefile': 'Makefile',
						'markdown': 'Markdown',
						'nginx': 'Nginx',
						'objectivec': 'Objective-C',
						'perl': 'Perl',
						'php': 'PHP',
						'python': 'Python',
                        'r':'R',
						'ruby': 'Ruby',
                        'scala':'Scala',
						'sql': 'SQL',
						'vbscript': 'VBScript',
						'xhtml': 'XHTML',
						'xml': 'XML'
					},
                                 
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            # 'fixed',
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'codesnippet',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',  
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
        ]),
    },
    'special':{
        'toolbar':'Special',
        'height': "200",
        'width': '100%',
        'toolbar_Special':[
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
             
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar',  'Iframe']},
            
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['ShowBlocks']},
        ]
    },

    'community_editor': {
        # 'skin': 'basic',
        # 'skin': 'office2013',
      
        'toolbar_communityConfig': [
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
             
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-']},
            {'name': 'links', 'items': ['Link', 'Unlink']},
            {'name': 'insert',
             'items': ['Image', 'Table', 'HorizontalRule',]},
            
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            
            '/',  # put this to force next toolbar on new line
            {'name': 'communitytools', 'items': [
                # put the name of your editor.ui.addButton here
                'Maximize',
                'CodeSnippet',
            ]},
        ],

     
        'toolbar': 'communityConfig',  # put selected toolbar config here
        'height': "70vh",
        'width': '100%',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
         'codeSnippet_languages' : {'apache': 'Apache',
						'bash': 'Bash',
						'coffeescript': 'CoffeeScript',
                        'c':'C',
						'cpp': 'C++',
						'cs': 'C#',
						'css': 'CSS',
						'diff': 'Diff',
						'html': 'HTML',
						'http': 'HTTP',
						'ini': 'INI',
						'java': 'Java',
						'javascript': 'JavaScript',
						'json': 'JSON',
						'makefile': 'Makefile',
						'markdown': 'Markdown',
						'nginx': 'Nginx',
						'objectivec': 'Objective-C',
						'perl': 'Perl',
						'php': 'PHP',
						'python': 'Python',
                        'r':'R',
						'ruby': 'Ruby',
                        'scala':'Scala',
						'sql': 'SQL',
						'vbscript': 'VBScript',
						'xhtml': 'XHTML',
						'xml': 'XML'
					},
                                 
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            'div',
            'codesnippet',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'elementspath',
        ]),
    },

    'comment_editor': {
        # 'skin': 'basic',
        # 'skin': 'office2013',
      
        'toolbar_communityConfig': [
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},             
            {'name': 'insert',
             'items': [ 'CodeSnippet',]},            
            '/',  # put this to force next toolbar on new line
        ],

     
        'toolbar': 'communityConfig',  # put selected toolbar config here
        'height': "250px",
        'width': '100%',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
         'codeSnippet_languages' : {'apache': 'Apache',
						'bash': 'Bash',
						'coffeescript': 'CoffeeScript',
                        'c':'C',
						'cpp': 'C++',
						'cs': 'C#',
						'css': 'CSS',
						'diff': 'Diff',
						'html': 'HTML',
						'http': 'HTTP',
						'ini': 'INI',
						'java': 'Java',
						'javascript': 'JavaScript',
						'json': 'JSON',
						'makefile': 'Makefile',
						'markdown': 'Markdown',
						'nginx': 'Nginx',
						'objectivec': 'Objective-C',
						'perl': 'Perl',
						'php': 'PHP',
						'python': 'Python',
                        'r':'R',
						'ruby': 'Ruby',
                        'scala':'Scala',
						'sql': 'SQL',
						'vbscript': 'VBScript',
						'xhtml': 'XHTML',
						'xml': 'XML'
					},
                                 
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            'div',
            'codesnippet',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'elementspath',
        ]),
    },
}
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_THUMBNAIL_SIZE = (50,50)
CKEDITOR_FORCE_JPEG_COMPRESSION = True
CKEDITOR_IMAGE_QUALITY  = 30
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_ALLOW_NONIMAGE_FILES = False
#ready for production

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'     #new
STATICFILES_DIRS = [BASE_DIR / 'static', ]      #new
MEDIA_ROOT = BASE_DIR /'media'
MEDIA_URL = "/media/"
LOGGING = LOGGING