# Generated by Django 4.0.3 on 2023-04-29 03:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tutorial Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tutorial Intro')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutorial_image', verbose_name='Tutorial Icon')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Category Name')),
                ('category_number', models.PositiveIntegerField(blank=True, null=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorialcategory', to='tutorial.tutorial', verbose_name='Select Tutorial')),
            ],
            options={
                'unique_together': {('tutorial', 'category', 'category_number')},
            },
        ),
        migrations.CreateModel(
            name='TutorialExamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exampletitle', models.CharField(max_length=200, verbose_name='Example Title')),
                ('examplelink', models.CharField(max_length=200, verbose_name='Example Link')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorialExamples', to='tutorial.tutorial', verbose_name='Select Tutorial')),
            ],
            options={
                'unique_together': {('tutorial', 'exampletitle', 'examplelink')},
            },
        ),
        migrations.CreateModel(
            name='TutorialArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('featured_image', models.ImageField(blank=True, upload_to='tutorial_images', verbose_name='Tutorial Featured Image')),
                ('status', models.CharField(choices=[('draft', 'drafted'), ('publish', 'published')], default='draft', max_length=7)),
                ('seoTitle', models.CharField(blank=True, default='Unknown', max_length=200, verbose_name='SEO Title')),
                ('seoDescription', models.TextField(blank=True, default='Unknown', max_length=500, verbose_name='SEO Description')),
                ('seoKeywords', models.CharField(blank=True, default='Unknown', max_length=200, verbose_name='SEO Keywords')),
                ('tutorial_number', models.PositiveIntegerField()),
                ('view_count', models.PositiveBigIntegerField(blank=True, default=1, null=True)),
                ('paralinks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tutorial Old Slugs')),
                ('tutorial', models.ForeignKey(help_text='Select the Tutorial Name with the corresponding category', on_delete=django.db.models.deletion.CASCADE, related_name='tutorialarticle', to='tutorial.tutorialcategory', verbose_name='Select Tutorial & Category')),
            ],
            options={
                'verbose_name_plural': 'Tutorial Articles',
                'ordering': ['-date_posted'],
                'unique_together': {('tutorial', 'tutorial_number')},
            },
        ),
    ]
