# Generated by Django 4.0.3 on 2023-04-29 03:46

import blog.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, help_text='Please enter the url for the blog eg python-introduction ', max_length=200, null=True, unique=True, verbose_name='URL')),
                ('featured_image', models.ImageField(blank=True, upload_to='post_images', verbose_name='Featured Image')),
                ('tags', models.CharField(blank=True, help_text='The tags should be in this format tag1, tag2, tag3,', max_length=200, null=True, validators=[blog.models.validate_tags])),
                ('status', models.CharField(choices=[('draft', 'drafted'), ('publish', 'published')], default='draft', max_length=7)),
                ('seoTitle', models.CharField(blank=True, default='Unknown', max_length=200, null=True, verbose_name='SEO Title')),
                ('seoDescription', models.TextField(blank=True, default='Unknown', max_length=1000, null=True, verbose_name='SEO Description')),
                ('seoKeywords', models.CharField(blank=True, default='Unknown', max_length=200, null=True, verbose_name='SEO Keywords')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('paralinks', models.TextField(blank=True, null=True, verbose_name='Post old Slugs')),
                ('post_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(blank=True, default='Uncategorized', related_name='posts', to='blog.category')),
            ],
            options={
                'verbose_name_plural': 'All Posts',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('approved_comment', models.BooleanField(default=False)),
                ('authorize_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'verbose_name_plural': 'All Comments',
                'ordering': ['-date_posted'],
            },
        ),
    ]
