# Generated by Django 4.0.3 on 2025-02-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_updated',
            field=models.DateTimeField(),
        ),
    ]
