# Generated by Django 4.0.3 on 2025-09-28 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_post_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BlogStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='blog.post')),
            ],
            options={
                'db_table': 'blog_stats',
            },
        ),
    ]
