# Generated by Django 4.0.3 on 2023-04-29 03:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Post Link')),
                ('slug', models.SlugField(blank=True, help_text='Please enter the url for the webstory eg python-story ', max_length=200, null=True, unique=True, verbose_name='URL')),
                ('status', models.CharField(choices=[('draft', 'drafted'), ('publish', 'published')], default='draft', max_length=7)),
                ('seoTitle', models.CharField(blank=True, default='Unknown', max_length=200, null=True, verbose_name='SEO Title')),
                ('seoDescription', models.TextField(blank=True, default='Unknown', max_length=1000, null=True, verbose_name='SEO Description')),
                ('seoKeywords', models.CharField(blank=True, default='Unknown', max_length=200, null=True, verbose_name='SEO Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coverimage', models.ImageField(blank=True, upload_to='story_images', verbose_name='Cover Image')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story', to='webstories.webstory')),
            ],
        ),
    ]
