# Generated by Django 4.0.3 on 2023-07-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstories', '0002_story_created_at_story_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='webstory',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webstory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
