# Generated by Django 4.0.3 on 2023-04-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insideads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Ads Title')),
                ('page', models.CharField(choices=[('tutorial', 'tutorial'), ('blog', 'blog')], default='blog', max_length=30, verbose_name='Select Page')),
                ('position', models.PositiveIntegerField(verbose_name='Paragraph Position')),
                ('script', models.TextField(verbose_name='Enter the Script')),
            ],
            options={
                'verbose_name_plural': 'Ad Inserter',
                'ordering': ['position'],
                'unique_together': {('page', 'position')},
            },
        ),
    ]
