# Generated by Django 4.0.3 on 2023-06-03 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insideads',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='insideads',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
