# Generated by Django 4.0.3 on 2023-07-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsmanager', '0002_insideads_created_at_insideads_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insideads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='insideads',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
