# Generated by Django 4.0.3 on 2025-10-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsmanager', '0004_alter_insideads_unique_together_insideads_placement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insideads',
            name='placement',
            field=models.CharField(blank=True, choices=[('global_header', 'Global header'), ('blog_sidebar', 'Blog sidebar'), ('blog_header', 'Blog header'), ('blog_footer', 'Blog footer'), ('blog_left_sidebar', 'Blog left sidebar'), ('blog_right_sidebar', 'Blog right sidebar'), ('blog_below_post', 'Blog below post'), ('blog_above_post', 'Blog above post'), ('blog_in_content', 'In Blog Content'), ('tutorial_sidebar', 'Tutorial sidebar'), ('tutorial_header', 'Tutorial header'), ('tutorial_footer', 'Tutorial footer'), ('tutorial_left_sidebar', 'Tutorial left sidebar'), ('tutorial_right_sidebar', 'Tutorial right sidebar'), ('tutorial_below_post', 'Tutorial below post'), ('tutorial_above_post', 'Tutorial above post'), ('tutorial_in_content', 'In Tutorial Content')], default=None, max_length=30, null=True, verbose_name='Select Placement'),
        ),
    ]
